djserver/djserver/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('glaceon.config')),
    url(r'^accounts/', include('allauth.urls')),
]

djserver/glaceon/apps/loadmap/urls.py
from django.urls import path
from .views import CourseDetailView, LoadmaplView

app_name = 'loadmap'
urlpatterns = [
    path('', LoadmaplView.as_view(), name='index'),
    path('detail/<slug:course_slug>/', CourseDetailView.as_view(), name="detail")
]

djserver/glaceon/apps/member/urls.py
from django.urls import path
from django.conf.urls import url, include
from .views import ProfileView, IndexView, MypageView

# app_name = 'member'
urlpatterns = [
    url(r'^mypage/$', MypageView.as_view(), name="mypage"),
    url(r'^(?P<username>[\w]+)/$', ProfileView.as_view(), name="profile")
]

djserver/glaceon/apps/loadmap/models.py
from django.db import models
from django.utils.translation import gettext as _

class Course(models.Model):
    title = models.CharField(_('Title'),max_length=255, blank=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(_('Description'), blank=True)

    def __str__(self):
        return self.title

    def get_title(self):
        title = self.title
        return title

djserver/glaceon/apps/member/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin


from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class UserProfile(models.Model):
    # ログイン用とは別の画面に表示される名前
    name = models.CharField("Handle Name", max_length=255)
    # user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
    #                             related_name='profile')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name='profile', primary_key=True)
    bio = models.TextField(blank=True)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.name

djserver/glaceon/apps/loadmap/views.py
from django.shortcuts import render

from .models import Course

from django.views.generic import DetailView, TemplateView, ListView

class LoadmaplView(ListView):
    model = Course

    template_name = 'glaceon/loadmap/browse.html'

class CourseDetailView(DetailView):

    model = Course

    template_name = 'glaceon/loadmap/detail.html'

    slug_url_kwarg = 'course_slug'
    slug_field = 'slug'

djserver/glaceon/apps/member/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .models import UserProfile

from django.views.generic import DetailView, TemplateView, ListView

class MypageView(DetailView):

    model = UserProfile

    template_name = 'glaceon/member/profile.html'

    def get_object(self):
        return get_object_or_404(self.model, name=self.request.user)

class ProfileView(DetailView):

    model = UserProfile

    template_name = 'glaceon/member/profile.html'

    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_object(self):
        # print("=====",self.request.user,"=====")
        return get_object_or_404(self.model, name=self.request.user)

class IndexView(TemplateView):
    template_name = 'glaceon/member/profile.html'

djserver/glaceon/templates/glaceon/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% if user.is_authenticated %}
        <p>Hello {{ user }} !<a href="{% url 'mypage' %}?next=/">Mypage</a></p>
    {% endif %}

	<h1>{% block pagetitle %}{% endblock %}</h1>
	{% block contents %}{% endblock %}

    {% if user.is_authenticated %}

        <p><a href="{% url 'account_logout' %}?next=/">Logout</a></p>
    {% else %}
        <p><a href="{% url 'account_login' %}?next=/">Login</a></p>
    {% endif %}
    <iframe width="1600" height="900" src="http://localhost:3000/" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</body>
</html>

djserver/glaceon/templates/glaceon/loadmap/browse.html
{% extends "glaceon/base.html" %}

{% block title %}
    Browse Courses
{% endblock %}

{% block pagetitle %}
    Course list
{% endblock %}

{% block contents %}
    <div>
        <ul>
            {% for course in object_list %}
                <li><a href="{% url 'loadmap:detail' course.title %}">{{ course.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

djserver/glaceon/templates/glaceon/loadmap/detail.html
{% extends "glaceon/base.html" %}

{% block title %}
    Course Detail
{% endblock %}

{% block pagetitle %}
    Course detail
{% endblock %}

{% block contents %}
    <div>
        <ul>
            <li>Course Title: {{ course.title }}</li>
            <li>Description: {{ course.description }}</li>
            <li>Description: {{ user.pk }}</li>
        </ul>
        <p>　　---------------------------</p>
        <p>　　ここにReactアプリケーションを立ち上げたい</p>
        <p>You're logged in with {{ user.get_provider }} as {{ user }}.</p>
    </div>
    <a href="{% url 'loadmap:index' %}">戻る</a>
{% endblock %}

djserver/glaceon/templates/glaceon/member/profile.html
{% extends "glaceon/base.html" %}

{% block title %}
    User Profile
{% endblock %}

{% block pagetitle %}
    User Profile
{% endblock %}

{% block contents %}
    <div>
        <ul>
            <li>Display Name: {{ userprofile.name }}</li>
            <li>bio: {{ userprofile.bio }}</li>
        </ul>
        <p>　　---------------------------</p>
        <p>　　ここにReactアプリケーションを立ち上げたい（かも？）</p>
    </div>
    <a href="{% url 'loadmap:index' %}">戻る</a>
{% endblock %}